apiVersion: kafka.strimzi.io/v1
kind: KafkaTopic
metadata:
  name: binance-raw-topic
  namespace: kafka
  labels:
    strimzi.io/cluster: kafka-cluster
spec:
  topicName: "binance.raw"
  partitions: 3
  replicas: 2
  config:
    retention.ms: 604800000
    segment.bytes: 1073741824
    min.insync.replicas: 1

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: binance-producer
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: binance-producer
  template:
    metadata:
      labels:
        app: binance-producer
    spec:
      terminationGracePeriodSeconds: 30
      imagePullSecrets:
        - name: github-registry-secret
      containers:
        - name: binance
          image: ghcr.io/${{ github.repository }}/binance-producer:latest
          imagePullPolicy: Always
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "kafka-cluster-kafka-bootstrap:9092"
            - name: BINANCE_TOPIC
              value: "binance.raw"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "300m"
              memory: "256Mi"