apiVersion: apps/v1
kind: Deployment
metadata:
  name: vcb-producer
  namespace: kafka
  labels:
    app: vcb-producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vcb-producer
  template:
    metadata:
      labels:
        app: vcb-producer
    spec:
      imagePullSecrets:
        - name: ghcr-auth
      containers:
      - name: vcb-producer

        image: ghcr.io/nu-xink-uit/kafka-intergration/vcb-producer:latest
        env:
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "kafka-service:9092"
        - name: VCB_TOPIC
          value: "vcb_exchange_rates"
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "256Mi"