apiVersion: apps/v1
kind: Deployment
metadata:
  name: binance-producer
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: binance-producer
  template:
    metadata:
      labels:
        app: binance-producer
    spec:
      terminationGracePeriodSeconds: 30
      imagePullSecrets:
        - name: ghcr-secret # Sử dụng secret đã tạo sẵn trong namespace kafka để pull image từ GHCR
      containers:
        - name: binance-streaming
          # Cập nhật đường dẫn image theo Organization của bạn
          image: ghcr.io/${{ github.repository_owner }}/binance-producer:latest
          imagePullPolicy: Always
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "my-cluster-1-kafka-bootstrap:9092"
            - name: BINANCE_WS_URL
              value: "wss://stream.binance.com:9443/ws/paxgusdt@ticker"
            - name: BINANCE_TOPIC
              value: "binance.raw"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"