apiVersion: apps/v1
kind: Deployment
metadata:
  name: binance-producer 
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: binance-producer
  template:
    metadata:
      labels:
        app: binance-producer
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: binance
          image: TEMP_IMAGE_WILL_BE_REPLACED_BY_SED
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "my-cluster-1-kafka-bootstrap:9092"
            - name: BINANCE_TOPIC
              value: "binance.raw"